name: Daily Kenya Weather Risk Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  run-weather-risk-pipeline:
    runs-on: ubuntu-latest

    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather risk pipeline
        run: |
          cd src
          python main.py